"""Add high column to market data

Revision ID: 6581dc9fe2b4
Revises: 2665df728788
Create Date: 2026-10-04 12:08:34.279214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6581dc9fe2b4'
down_revision: Union[str, Sequence[str], None] = '2665df728788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('high', sa.Float(), nullable=False))
    op.add_column('market_data', sa.Column('volume', sa.Float(), nullable=False))
    op.drop_column('market_data', 'Volume')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('Volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('market_data', 'volume')
    op.drop_column('market_data', 'high')
    # ### end Alembic commands ###
